// ============================================
// Instrument Presets
// ============================================

import type { InstrumentPreset } from '../types';
import { CHORD_LIBRARY, NOTE_COLORS } from './chords';

export const INSTRUMENTS: InstrumentPreset[] = [
  // ==========================================
  // KEYS
  // ==========================================
  {
    id: 'piano',
    name: 'Grand Piano',
    icon: 'piano',
    description: 'Classic acoustic grand piano with rich harmonics',
    category: 'keys',
    instrument: 0,
    left: {
      thumb: { name: 'C', notes: CHORD_LIBRARY['C'], color: NOTE_COLORS.red },
      index: { name: 'G', notes: CHORD_LIBRARY['G'], color: NOTE_COLORS.green },
      middle: { name: 'Am', notes: CHORD_LIBRARY['Am'], color: NOTE_COLORS.blue },
      ring: { name: 'F', notes: CHORD_LIBRARY['F'], color: NOTE_COLORS.amber },
      pinky: { name: 'Dm', notes: CHORD_LIBRARY['Dm'], color: NOTE_COLORS.purple },
    },
    right: {
      thumb: { name: 'Em', notes: CHORD_LIBRARY['Em'], color: NOTE_COLORS.pink },
      index: { name: 'C7', notes: CHORD_LIBRARY['C7'], color: NOTE_COLORS.teal },
      middle: { name: 'G7', notes: CHORD_LIBRARY['G7'], color: NOTE_COLORS.gold },
      ring: { name: 'Am7', notes: CHORD_LIBRARY['Am7'], color: NOTE_COLORS.violet },
      pinky: { name: 'Fmaj7', notes: CHORD_LIBRARY['Fmaj7'], color: NOTE_COLORS.cyan },
    },
  },

  {
    id: 'bright-piano',
    name: 'Bright Piano',
    icon: 'piano',
    description: 'Crisp and bright acoustic piano',
    category: 'keys',
    instrument: 1,
    left: {
      thumb: { name: 'C', notes: CHORD_LIBRARY['C'], color: '#F8F9FA' },
      index: { name: 'G', notes: CHORD_LIBRARY['G'], color: '#E9ECEF' },
      middle: { name: 'Am', notes: CHORD_LIBRARY['Am'], color: '#DEE2E6' },
      ring: { name: 'F', notes: CHORD_LIBRARY['F'], color: '#CED4DA' },
      pinky: { name: 'Dm', notes: CHORD_LIBRARY['Dm'], color: '#ADB5BD' },
    },
    right: {
      thumb: { name: 'Em', notes: CHORD_LIBRARY['Em'], color: '#6C757D' },
      index: { name: 'Cmaj7', notes: CHORD_LIBRARY['Cmaj7'], color: '#495057' },
      middle: { name: 'Fmaj7', notes: CHORD_LIBRARY['Fmaj7'], color: '#343A40' },
      ring: { name: 'G7', notes: CHORD_LIBRARY['G7'], color: '#212529' },
      pinky: { name: 'Am7', notes: CHORD_LIBRARY['Am7'], color: '#F8F9FA' },
    },
  },

  {
    id: 'electric-piano',
    name: 'Electric Piano',
    icon: 'piano',
    description: 'Smooth Rhodes-style electric piano',
    category: 'keys',
    instrument: 4,
    left: {
      thumb: { name: 'Cmaj7', notes: CHORD_LIBRARY['Cmaj7'], color: '#E8D5B7' },
      index: { name: 'Dm7', notes: CHORD_LIBRARY['Dm7'], color: '#D4A574' },
      middle: { name: 'Em7', notes: CHORD_LIBRARY['Em7'], color: '#C9A86C' },
      ring: { name: 'Fmaj7', notes: CHORD_LIBRARY['Fmaj7'], color: '#DAA520' },
      pinky: { name: 'G7', notes: CHORD_LIBRARY['G7'], color: '#B8860B' },
    },
    right: {
      thumb: { name: 'Am7', notes: CHORD_LIBRARY['Am7'], color: '#CD853F' },
      index: { name: 'Bm7', notes: CHORD_LIBRARY['Bm7'], color: '#DEB887' },
      middle: { name: 'C', notes: CHORD_LIBRARY['C'], color: '#F5DEB3' },
      ring: { name: 'D7', notes: CHORD_LIBRARY['D7'], color: '#FFDEAD' },
      pinky: { name: 'E7', notes: CHORD_LIBRARY['E7'], color: '#FFE4B5' },
    },
  },

  {
    id: 'honky-tonk',
    name: 'Honky Tonk Piano',
    icon: 'piano',
    description: 'Detuned saloon-style piano',
    category: 'keys',
    instrument: 3,
    left: {
      thumb: { name: 'C', notes: CHORD_LIBRARY['C'], color: '#8B4513' },
      index: { name: 'F', notes: CHORD_LIBRARY['F'], color: '#A0522D' },
      middle: { name: 'G7', notes: CHORD_LIBRARY['G7'], color: '#CD853F' },
      ring: { name: 'C7', notes: CHORD_LIBRARY['C7'], color: '#D2691E' },
      pinky: { name: 'D7', notes: CHORD_LIBRARY['D7'], color: '#B8860B' },
    },
    right: {
      thumb: { name: 'E7', notes: CHORD_LIBRARY['E7'], color: '#DAA520' },
      index: { name: 'A7', notes: CHORD_LIBRARY['A7'], color: '#F4A460' },
      middle: { name: 'G', notes: CHORD_LIBRARY['G'], color: '#DEB887' },
      ring: { name: 'F', notes: CHORD_LIBRARY['F'], color: '#FFDEAD' },
      pinky: { name: 'Am', notes: CHORD_LIBRARY['Am'], color: '#FFE4B5' },
    },
  },

  {
    id: 'jazz-piano',
    name: 'Jazz Piano',
    icon: 'piano',
    description: 'Sophisticated jazz voicings',
    category: 'keys',
    instrument: 0,
    left: {
      thumb: { name: 'Dm7', notes: CHORD_LIBRARY['Dm7'], color: '#D4A574' },
      index: { name: 'G7', notes: CHORD_LIBRARY['G7'], color: '#C9A86C' },
      middle: { name: 'Cmaj7', notes: CHORD_LIBRARY['Cmaj7'], color: '#E8D5B7' },
      ring: { name: 'Am7', notes: CHORD_LIBRARY['Am7'], color: '#B8860B' },
      pinky: { name: 'Em7', notes: CHORD_LIBRARY['Em7'], color: '#DAA520' },
    },
    right: {
      thumb: { name: 'Fmaj7', notes: CHORD_LIBRARY['Fmaj7'], color: '#CD853F' },
      index: { name: 'Bm7', notes: CHORD_LIBRARY['Bm7'], color: '#DEB887' },
      middle: { name: 'E7', notes: CHORD_LIBRARY['E7'], color: '#F5DEB3' },
      ring: { name: 'A7', notes: CHORD_LIBRARY['A7'], color: '#FFDEAD' },
      pinky: { name: 'D7', notes: CHORD_LIBRARY['D7'], color: '#FFE4B5' },
    },
  },

  {
    id: 'harpsichord',
    name: 'Harpsichord',
    icon: 'piano',
    description: 'Baroque plucked keyboard',
    category: 'keys',
    instrument: 6,
    left: {
      thumb: { name: 'C', notes: CHORD_LIBRARY['C'], color: '#8B0000' },
      index: { name: 'Dm', notes: CHORD_LIBRARY['Dm'], color: '#A52A2A' },
      middle: { name: 'Em', notes: CHORD_LIBRARY['Em'], color: '#B22222' },
      ring: { name: 'F', notes: CHORD_LIBRARY['F'], color: '#DC143C' },
      pinky: { name: 'G', notes: CHORD_LIBRARY['G'], color: '#CD5C5C' },
    },
    right: {
      thumb: { name: 'Am', notes: CHORD_LIBRARY['Am'], color: '#FFD700' },
      index: { name: 'Bdim', notes: CHORD_LIBRARY['Bdim'], color: '#DAA520' },
      middle: { name: 'Cmaj7', notes: CHORD_LIBRARY['Cmaj7'], color: '#B8860B' },
      ring: { name: 'Dm7', notes: CHORD_LIBRARY['Dm7'], color: '#CD853F' },
      pinky: { name: 'E7', notes: CHORD_LIBRARY['E7'], color: '#D2691E' },
    },
  },

  {
    id: 'clavinet',
    name: 'Clavinet',
    icon: 'piano',
    description: 'Funky electric clavinet',
    category: 'keys',
    instrument: 7,
    left: {
      thumb: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#FF6B00' },
      index: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#FF8500' },
      middle: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#FFA000' },
      ring: { name: 'F4', notes: CHORD_LIBRARY['F4'], color: '#FFB800' },
      pinky: { name: 'G4', notes: CHORD_LIBRARY['G4'], color: '#FFD000' },
    },
    right: {
      thumb: { name: 'A4', notes: CHORD_LIBRARY['A4'], color: '#E65100' },
      index: { name: 'B4', notes: CHORD_LIBRARY['B4'], color: '#EF6C00' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#F57C00' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#FB8C00' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#FF9800' },
    },
  },

  {
    id: 'celesta',
    name: 'Celesta',
    icon: 'bell',
    description: 'Delicate bell-like keyboard',
    category: 'keys',
    instrument: 8,
    left: {
      thumb: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#E8F4FD' },
      index: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#D4E9FA' },
      middle: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#BBDEFB' },
      ring: { name: 'F5', notes: CHORD_LIBRARY['F5'], color: '#90CAF9' },
      pinky: { name: 'G5', notes: CHORD_LIBRARY['G5'], color: '#64B5F6' },
    },
    right: {
      thumb: { name: 'A5', notes: CHORD_LIBRARY['A5'], color: '#42A5F5' },
      index: { name: 'B5', notes: CHORD_LIBRARY['B5'], color: '#2196F3' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#1E88E5' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#1976D2' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#1565C0' },
    },
  },

  {
    id: 'organ',
    name: 'Church Organ',
    icon: 'organ',
    description: 'Majestic pipe organ tones',
    category: 'keys',
    instrument: 19,
    left: {
      thumb: { name: 'C', notes: CHORD_LIBRARY['C'], color: '#8B4513' },
      index: { name: 'F', notes: CHORD_LIBRARY['F'], color: '#A0522D' },
      middle: { name: 'G', notes: CHORD_LIBRARY['G'], color: '#CD853F' },
      ring: { name: 'Am', notes: CHORD_LIBRARY['Am'], color: '#DEB887' },
      pinky: { name: 'Em', notes: CHORD_LIBRARY['Em'], color: '#D2691E' },
    },
    right: {
      thumb: { name: 'Dm', notes: CHORD_LIBRARY['Dm'], color: '#8B0000' },
      index: { name: 'Cmaj7', notes: CHORD_LIBRARY['Cmaj7'], color: '#B22222' },
      middle: { name: 'Fmaj7', notes: CHORD_LIBRARY['Fmaj7'], color: '#DC143C' },
      ring: { name: 'Gmaj7', notes: CHORD_LIBRARY['Gmaj7'], color: '#CD5C5C' },
      pinky: { name: 'Am7', notes: CHORD_LIBRARY['Am7'], color: '#F08080' },
    },
  },

  {
    id: 'rock-organ',
    name: 'Rock Organ',
    icon: 'organ',
    description: 'Distorted Hammond-style organ',
    category: 'keys',
    instrument: 18,
    left: {
      thumb: { name: 'C', notes: CHORD_LIBRARY['C'], color: '#FF4500' },
      index: { name: 'F', notes: CHORD_LIBRARY['F'], color: '#FF6347' },
      middle: { name: 'G', notes: CHORD_LIBRARY['G'], color: '#FF7F50' },
      ring: { name: 'Am', notes: CHORD_LIBRARY['Am'], color: '#FF8C00' },
      pinky: { name: 'Dm', notes: CHORD_LIBRARY['Dm'], color: '#FFA500' },
    },
    right: {
      thumb: { name: 'Em', notes: CHORD_LIBRARY['Em'], color: '#DC143C' },
      index: { name: 'C7', notes: CHORD_LIBRARY['C7'], color: '#B22222' },
      middle: { name: 'G7', notes: CHORD_LIBRARY['G7'], color: '#8B0000' },
      ring: { name: 'D7', notes: CHORD_LIBRARY['D7'], color: '#A52A2A' },
      pinky: { name: 'E7', notes: CHORD_LIBRARY['E7'], color: '#CD5C5C' },
    },
  },

  {
    id: 'accordion',
    name: 'Accordion',
    icon: 'organ',
    description: 'Traditional accordion sound',
    category: 'keys',
    instrument: 21,
    left: {
      thumb: { name: 'C', notes: CHORD_LIBRARY['C'], color: '#E53935' },
      index: { name: 'G', notes: CHORD_LIBRARY['G'], color: '#D32F2F' },
      middle: { name: 'F', notes: CHORD_LIBRARY['F'], color: '#C62828' },
      ring: { name: 'Am', notes: CHORD_LIBRARY['Am'], color: '#B71C1C' },
      pinky: { name: 'Dm', notes: CHORD_LIBRARY['Dm'], color: '#FF5252' },
    },
    right: {
      thumb: { name: 'Em', notes: CHORD_LIBRARY['Em'], color: '#212121' },
      index: { name: 'G7', notes: CHORD_LIBRARY['G7'], color: '#424242' },
      middle: { name: 'C7', notes: CHORD_LIBRARY['C7'], color: '#616161' },
      ring: { name: 'D7', notes: CHORD_LIBRARY['D7'], color: '#757575' },
      pinky: { name: 'A7', notes: CHORD_LIBRARY['A7'], color: '#9E9E9E' },
    },
  },

  {
    id: 'harmonica',
    name: 'Harmonica',
    icon: 'organ',
    description: 'Blues harmonica',
    category: 'keys',
    instrument: 22,
    left: {
      thumb: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#1565C0' },
      index: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#1976D2' },
      middle: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#1E88E5' },
      ring: { name: 'G4', notes: CHORD_LIBRARY['G4'], color: '#2196F3' },
      pinky: { name: 'A4', notes: CHORD_LIBRARY['A4'], color: '#42A5F5' },
    },
    right: {
      thumb: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#0D47A1' },
      index: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#1565C0' },
      middle: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#1976D2' },
      ring: { name: 'G5', notes: CHORD_LIBRARY['G5'], color: '#1E88E5' },
      pinky: { name: 'A5', notes: CHORD_LIBRARY['A5'], color: '#2196F3' },
    },
  },

  // ==========================================
  // STRINGS
  // ==========================================
  {
    id: 'guitar',
    name: 'Electric Guitar',
    icon: 'guitar',
    description: 'Clean electric guitar tone',
    category: 'strings',
    instrument: 27,
    left: {
      thumb: { name: 'C', notes: CHORD_LIBRARY['C'], color: '#E74C3C' },
      index: { name: 'G', notes: CHORD_LIBRARY['G'], color: '#E67E22' },
      middle: { name: 'D', notes: CHORD_LIBRARY['D'], color: '#F1C40F' },
      ring: { name: 'A', notes: CHORD_LIBRARY['A'], color: '#2ECC71' },
      pinky: { name: 'E', notes: CHORD_LIBRARY['E'], color: '#3498DB' },
    },
    right: {
      thumb: { name: 'Am', notes: CHORD_LIBRARY['Am'], color: '#9B59B6' },
      index: { name: 'Em', notes: CHORD_LIBRARY['Em'], color: '#1ABC9C' },
      middle: { name: 'Dm', notes: CHORD_LIBRARY['Dm'], color: '#34495E' },
      ring: { name: 'Bm', notes: CHORD_LIBRARY['Bm'], color: '#E91E63' },
      pinky: { name: 'F', notes: CHORD_LIBRARY['F'], color: '#00BCD4' },
    },
  },

  {
    id: 'acoustic-guitar',
    name: 'Acoustic Guitar',
    icon: 'guitar',
    description: 'Warm acoustic steel strings',
    category: 'strings',
    instrument: 25,
    left: {
      thumb: { name: 'C', notes: CHORD_LIBRARY['C'], color: '#D4A574' },
      index: { name: 'G', notes: CHORD_LIBRARY['G'], color: '#C9A86C' },
      middle: { name: 'D', notes: CHORD_LIBRARY['D'], color: '#E8D5B7' },
      ring: { name: 'A', notes: CHORD_LIBRARY['A'], color: '#B8860B' },
      pinky: { name: 'E', notes: CHORD_LIBRARY['E'], color: '#DAA520' },
    },
    right: {
      thumb: { name: 'Am', notes: CHORD_LIBRARY['Am'], color: '#CD853F' },
      index: { name: 'Em', notes: CHORD_LIBRARY['Em'], color: '#DEB887' },
      middle: { name: 'Dm', notes: CHORD_LIBRARY['Dm'], color: '#F5DEB3' },
      ring: { name: 'F', notes: CHORD_LIBRARY['F'], color: '#FFDEAD' },
      pinky: { name: 'Bm', notes: CHORD_LIBRARY['Bm'], color: '#FFE4B5' },
    },
  },

  {
    id: 'nylon-guitar',
    name: 'Nylon Guitar',
    icon: 'guitar',
    description: 'Classical nylon string guitar',
    category: 'strings',
    instrument: 24,
    left: {
      thumb: { name: 'Am', notes: CHORD_LIBRARY['Am'], color: '#8D6E63' },
      index: { name: 'E', notes: CHORD_LIBRARY['E'], color: '#A1887F' },
      middle: { name: 'Dm', notes: CHORD_LIBRARY['Dm'], color: '#BCAAA4' },
      ring: { name: 'G', notes: CHORD_LIBRARY['G'], color: '#D7CCC8' },
      pinky: { name: 'C', notes: CHORD_LIBRARY['C'], color: '#EFEBE9' },
    },
    right: {
      thumb: { name: 'F', notes: CHORD_LIBRARY['F'], color: '#5D4037' },
      index: { name: 'Em7', notes: CHORD_LIBRARY['Em7'], color: '#6D4C41' },
      middle: { name: 'Am7', notes: CHORD_LIBRARY['Am7'], color: '#795548' },
      ring: { name: 'Dm7', notes: CHORD_LIBRARY['Dm7'], color: '#8D6E63' },
      pinky: { name: 'Gmaj7', notes: CHORD_LIBRARY['Gmaj7'], color: '#A1887F' },
    },
  },

  {
    id: 'overdriven-guitar',
    name: 'Overdriven Guitar',
    icon: 'guitar',
    description: 'Crunchy overdriven tone',
    category: 'strings',
    instrument: 29,
    left: {
      thumb: { name: 'E', notes: CHORD_LIBRARY['E'], color: '#FF1744' },
      index: { name: 'A', notes: CHORD_LIBRARY['A'], color: '#F50057' },
      middle: { name: 'D', notes: CHORD_LIBRARY['D'], color: '#D500F9' },
      ring: { name: 'G', notes: CHORD_LIBRARY['G'], color: '#651FFF' },
      pinky: { name: 'C', notes: CHORD_LIBRARY['C'], color: '#3D5AFE' },
    },
    right: {
      thumb: { name: 'Em', notes: CHORD_LIBRARY['Em'], color: '#00E676' },
      index: { name: 'Am', notes: CHORD_LIBRARY['Am'], color: '#76FF03' },
      middle: { name: 'Dm', notes: CHORD_LIBRARY['Dm'], color: '#FFEA00' },
      ring: { name: 'Bm', notes: CHORD_LIBRARY['Bm'], color: '#FF9100' },
      pinky: { name: 'F', notes: CHORD_LIBRARY['F'], color: '#FF3D00' },
    },
  },

  {
    id: 'distortion-guitar',
    name: 'Distortion Guitar',
    icon: 'guitar',
    description: 'Heavy metal distortion',
    category: 'strings',
    instrument: 30,
    left: {
      thumb: { name: 'E', notes: CHORD_LIBRARY['E'], color: '#B71C1C' },
      index: { name: 'A', notes: CHORD_LIBRARY['A'], color: '#880E4F' },
      middle: { name: 'D', notes: CHORD_LIBRARY['D'], color: '#4A148C' },
      ring: { name: 'G', notes: CHORD_LIBRARY['G'], color: '#311B92' },
      pinky: { name: 'C', notes: CHORD_LIBRARY['C'], color: '#1A237E' },
    },
    right: {
      thumb: { name: 'Em', notes: CHORD_LIBRARY['Em'], color: '#263238' },
      index: { name: 'Am', notes: CHORD_LIBRARY['Am'], color: '#37474F' },
      middle: { name: 'Bm', notes: CHORD_LIBRARY['Bm'], color: '#455A64' },
      ring: { name: 'Dm', notes: CHORD_LIBRARY['Dm'], color: '#546E7A' },
      pinky: { name: 'F', notes: CHORD_LIBRARY['F'], color: '#607D8B' },
    },
  },

  {
    id: 'orchestra-strings',
    name: 'Orchestra Strings',
    icon: 'violin',
    description: 'Lush orchestral string ensemble',
    category: 'strings',
    instrument: 48,
    left: {
      thumb: { name: 'C', notes: CHORD_LIBRARY['C'], color: '#8B4513' },
      index: { name: 'Am', notes: CHORD_LIBRARY['Am'], color: '#A0522D' },
      middle: { name: 'F', notes: CHORD_LIBRARY['F'], color: '#CD853F' },
      ring: { name: 'G', notes: CHORD_LIBRARY['G'], color: '#DEB887' },
      pinky: { name: 'Em', notes: CHORD_LIBRARY['Em'], color: '#D2691E' },
    },
    right: {
      thumb: { name: 'Dm', notes: CHORD_LIBRARY['Dm'], color: '#8B0000' },
      index: { name: 'Cmaj7', notes: CHORD_LIBRARY['Cmaj7'], color: '#B22222' },
      middle: { name: 'Fmaj7', notes: CHORD_LIBRARY['Fmaj7'], color: '#DC143C' },
      ring: { name: 'Am7', notes: CHORD_LIBRARY['Am7'], color: '#CD5C5C' },
      pinky: { name: 'Gmaj7', notes: CHORD_LIBRARY['Gmaj7'], color: '#F08080' },
    },
  },

  {
    id: 'violin',
    name: 'Solo Violin',
    icon: 'violin',
    description: 'Expressive solo violin',
    category: 'strings',
    instrument: 40,
    left: {
      thumb: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#8B4513' },
      index: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#A0522D' },
      middle: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#CD853F' },
      ring: { name: 'F4', notes: CHORD_LIBRARY['F4'], color: '#DEB887' },
      pinky: { name: 'G4', notes: CHORD_LIBRARY['G4'], color: '#D2691E' },
    },
    right: {
      thumb: { name: 'A4', notes: CHORD_LIBRARY['A4'], color: '#F4A460' },
      index: { name: 'B4', notes: CHORD_LIBRARY['B4'], color: '#FFDAB9' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#FFE4B5' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#FFE4C4' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#FFEFD5' },
    },
  },

  {
    id: 'cello',
    name: 'Solo Cello',
    icon: 'violin',
    description: 'Rich and warm cello',
    category: 'strings',
    instrument: 42,
    left: {
      thumb: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#3E2723' },
      index: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#4E342E' },
      middle: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#5D4037' },
      ring: { name: 'F4', notes: CHORD_LIBRARY['F4'], color: '#6D4C41' },
      pinky: { name: 'G4', notes: CHORD_LIBRARY['G4'], color: '#795548' },
    },
    right: {
      thumb: { name: 'A4', notes: CHORD_LIBRARY['A4'], color: '#8D6E63' },
      index: { name: 'B4', notes: CHORD_LIBRARY['B4'], color: '#A1887F' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#BCAAA4' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#D7CCC8' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#EFEBE9' },
    },
  },

  {
    id: 'pizzicato',
    name: 'Pizzicato Strings',
    icon: 'violin',
    description: 'Plucked orchestral strings',
    category: 'strings',
    instrument: 45,
    left: {
      thumb: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#FF7043' },
      index: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#FF8A65' },
      middle: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#FFAB91' },
      ring: { name: 'F4', notes: CHORD_LIBRARY['F4'], color: '#FFCCBC' },
      pinky: { name: 'G4', notes: CHORD_LIBRARY['G4'], color: '#FBE9E7' },
    },
    right: {
      thumb: { name: 'A4', notes: CHORD_LIBRARY['A4'], color: '#FF5722' },
      index: { name: 'B4', notes: CHORD_LIBRARY['B4'], color: '#F4511E' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#E64A19' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#D84315' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#BF360C' },
    },
  },

  {
    id: 'bass',
    name: 'Electric Bass',
    icon: 'bass',
    description: 'Punchy electric bass guitar',
    category: 'strings',
    instrument: 33,
    left: {
      thumb: { name: 'BassC', notes: CHORD_LIBRARY['BassC'], color: '#1A237E' },
      index: { name: 'BassD', notes: CHORD_LIBRARY['BassD'], color: '#283593' },
      middle: { name: 'BassE', notes: CHORD_LIBRARY['BassE'], color: '#303F9F' },
      ring: { name: 'BassF', notes: CHORD_LIBRARY['BassF'], color: '#3949AB' },
      pinky: { name: 'BassG', notes: CHORD_LIBRARY['BassG'], color: '#3F51B5' },
    },
    right: {
      thumb: { name: 'BassA', notes: CHORD_LIBRARY['BassA'], color: '#5C6BC0' },
      index: { name: 'BassB', notes: CHORD_LIBRARY['BassB'], color: '#7986CB' },
      middle: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#9FA8DA' },
      ring: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#C5CAE9' },
      pinky: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#E8EAF6' },
    },
  },

  {
    id: 'slap-bass',
    name: 'Slap Bass',
    icon: 'bass',
    description: 'Funky slap bass sound',
    category: 'strings',
    instrument: 36,
    left: {
      thumb: { name: 'BassC', notes: CHORD_LIBRARY['BassC'], color: '#FF6F00' },
      index: { name: 'BassD', notes: CHORD_LIBRARY['BassD'], color: '#FF8F00' },
      middle: { name: 'BassE', notes: CHORD_LIBRARY['BassE'], color: '#FFA000' },
      ring: { name: 'BassF', notes: CHORD_LIBRARY['BassF'], color: '#FFB300' },
      pinky: { name: 'BassG', notes: CHORD_LIBRARY['BassG'], color: '#FFC107' },
    },
    right: {
      thumb: { name: 'BassA', notes: CHORD_LIBRARY['BassA'], color: '#E65100' },
      index: { name: 'BassB', notes: CHORD_LIBRARY['BassB'], color: '#EF6C00' },
      middle: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#F57C00' },
      ring: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#FB8C00' },
      pinky: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#FF9800' },
    },
  },

  {
    id: 'synth-bass',
    name: 'Synth Bass',
    icon: 'bass',
    description: 'Deep synthesizer bass',
    category: 'strings',
    instrument: 38,
    left: {
      thumb: { name: 'BassC', notes: CHORD_LIBRARY['BassC'], color: '#7C4DFF' },
      index: { name: 'BassD', notes: CHORD_LIBRARY['BassD'], color: '#651FFF' },
      middle: { name: 'BassE', notes: CHORD_LIBRARY['BassE'], color: '#6200EA' },
      ring: { name: 'BassF', notes: CHORD_LIBRARY['BassF'], color: '#304FFE' },
      pinky: { name: 'BassG', notes: CHORD_LIBRARY['BassG'], color: '#2962FF' },
    },
    right: {
      thumb: { name: 'BassA', notes: CHORD_LIBRARY['BassA'], color: '#AA00FF' },
      index: { name: 'BassB', notes: CHORD_LIBRARY['BassB'], color: '#D500F9' },
      middle: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#E040FB' },
      ring: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#EA80FC' },
      pinky: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#B388FF' },
    },
  },

  {
    id: 'harp',
    name: 'Concert Harp',
    icon: 'harp',
    description: 'Elegant classical harp',
    category: 'strings',
    instrument: 46,
    left: {
      thumb: { name: 'Cmaj7', notes: CHORD_LIBRARY['Cmaj7'], color: '#FFD700' },
      index: { name: 'Dm7', notes: CHORD_LIBRARY['Dm7'], color: '#FFA500' },
      middle: { name: 'Em7', notes: CHORD_LIBRARY['Em7'], color: '#FF8C00' },
      ring: { name: 'Fmaj7', notes: CHORD_LIBRARY['Fmaj7'], color: '#FF7F50' },
      pinky: { name: 'G7', notes: CHORD_LIBRARY['G7'], color: '#FF6347' },
    },
    right: {
      thumb: { name: 'Am7', notes: CHORD_LIBRARY['Am7'], color: '#FFE4B5' },
      index: { name: 'Bm7', notes: CHORD_LIBRARY['Bm7'], color: '#FFDAB9' },
      middle: { name: 'Cmaj7', notes: CHORD_LIBRARY['Cmaj7'], color: '#FFE4C4' },
      ring: { name: 'Dm7', notes: CHORD_LIBRARY['Dm7'], color: '#FFEFD5' },
      pinky: { name: 'Em7', notes: CHORD_LIBRARY['Em7'], color: '#FFF8DC' },
    },
  },

  // ==========================================
  // BRASS
  // ==========================================
  {
    id: 'brass-ensemble',
    name: 'Brass Ensemble',
    icon: 'brass',
    description: 'Powerful brass section',
    category: 'brass',
    instrument: 61,
    left: {
      thumb: { name: 'C', notes: CHORD_LIBRARY['C'], color: '#FFD700' },
      index: { name: 'F', notes: CHORD_LIBRARY['F'], color: '#FFA500' },
      middle: { name: 'G', notes: CHORD_LIBRARY['G'], color: '#FF8C00' },
      ring: { name: 'Dm', notes: CHORD_LIBRARY['Dm'], color: '#FF7F50' },
      pinky: { name: 'Am', notes: CHORD_LIBRARY['Am'], color: '#FF6347' },
    },
    right: {
      thumb: { name: 'Em', notes: CHORD_LIBRARY['Em'], color: '#DAA520' },
      index: { name: 'Cmaj7', notes: CHORD_LIBRARY['Cmaj7'], color: '#B8860B' },
      middle: { name: 'Fmaj7', notes: CHORD_LIBRARY['Fmaj7'], color: '#CD853F' },
      ring: { name: 'G7', notes: CHORD_LIBRARY['G7'], color: '#D2691E' },
      pinky: { name: 'Am7', notes: CHORD_LIBRARY['Am7'], color: '#8B4513' },
    },
  },

  {
    id: 'trumpet',
    name: 'Trumpet',
    icon: 'brass',
    description: 'Bright jazz trumpet',
    category: 'brass',
    instrument: 56,
    left: {
      thumb: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#FFD700' },
      index: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#FFA500' },
      middle: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#FF8C00' },
      ring: { name: 'F4', notes: CHORD_LIBRARY['F4'], color: '#FF7F50' },
      pinky: { name: 'G4', notes: CHORD_LIBRARY['G4'], color: '#FF6347' },
    },
    right: {
      thumb: { name: 'A4', notes: CHORD_LIBRARY['A4'], color: '#DAA520' },
      index: { name: 'B4', notes: CHORD_LIBRARY['B4'], color: '#B8860B' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#CD853F' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#D2691E' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#8B4513' },
    },
  },

  {
    id: 'muted-trumpet',
    name: 'Muted Trumpet',
    icon: 'brass',
    description: 'Muted jazz trumpet',
    category: 'brass',
    instrument: 59,
    left: {
      thumb: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#FFAB91' },
      index: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#FFCCBC' },
      middle: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#FBE9E7' },
      ring: { name: 'F4', notes: CHORD_LIBRARY['F4'], color: '#FF8A65' },
      pinky: { name: 'G4', notes: CHORD_LIBRARY['G4'], color: '#FF7043' },
    },
    right: {
      thumb: { name: 'A4', notes: CHORD_LIBRARY['A4'], color: '#FF5722' },
      index: { name: 'B4', notes: CHORD_LIBRARY['B4'], color: '#F4511E' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#E64A19' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#D84315' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#BF360C' },
    },
  },

  {
    id: 'trombone',
    name: 'Trombone',
    icon: 'brass',
    description: 'Smooth jazz trombone',
    category: 'brass',
    instrument: 57,
    left: {
      thumb: { name: 'C', notes: CHORD_LIBRARY['C'], color: '#B8860B' },
      index: { name: 'D', notes: CHORD_LIBRARY['D'], color: '#CD853F' },
      middle: { name: 'F', notes: CHORD_LIBRARY['F'], color: '#DAA520' },
      ring: { name: 'G', notes: CHORD_LIBRARY['G'], color: '#D2691E' },
      pinky: { name: 'A', notes: CHORD_LIBRARY['A'], color: '#8B4513' },
    },
    right: {
      thumb: { name: 'Dm', notes: CHORD_LIBRARY['Dm'], color: '#FFD700' },
      index: { name: 'Em', notes: CHORD_LIBRARY['Em'], color: '#FFA500' },
      middle: { name: 'Am', notes: CHORD_LIBRARY['Am'], color: '#FF8C00' },
      ring: { name: 'Bm', notes: CHORD_LIBRARY['Bm'], color: '#FF7F50' },
      pinky: { name: 'Cm', notes: CHORD_LIBRARY['Cm'], color: '#FF6347' },
    },
  },

  {
    id: 'french-horn',
    name: 'French Horn',
    icon: 'brass',
    description: 'Majestic orchestral horn',
    category: 'brass',
    instrument: 60,
    left: {
      thumb: { name: 'C', notes: CHORD_LIBRARY['C'], color: '#5D4037' },
      index: { name: 'F', notes: CHORD_LIBRARY['F'], color: '#6D4C41' },
      middle: { name: 'G', notes: CHORD_LIBRARY['G'], color: '#795548' },
      ring: { name: 'Am', notes: CHORD_LIBRARY['Am'], color: '#8D6E63' },
      pinky: { name: 'Dm', notes: CHORD_LIBRARY['Dm'], color: '#A1887F' },
    },
    right: {
      thumb: { name: 'Em', notes: CHORD_LIBRARY['Em'], color: '#BCAAA4' },
      index: { name: 'Cmaj7', notes: CHORD_LIBRARY['Cmaj7'], color: '#D7CCC8' },
      middle: { name: 'Fmaj7', notes: CHORD_LIBRARY['Fmaj7'], color: '#EFEBE9' },
      ring: { name: 'Gmaj7', notes: CHORD_LIBRARY['Gmaj7'], color: '#3E2723' },
      pinky: { name: 'Am7', notes: CHORD_LIBRARY['Am7'], color: '#4E342E' },
    },
  },

  {
    id: 'tuba',
    name: 'Tuba',
    icon: 'brass',
    description: 'Deep brass tuba',
    category: 'brass',
    instrument: 58,
    left: {
      thumb: { name: 'BassC', notes: CHORD_LIBRARY['BassC'], color: '#3E2723' },
      index: { name: 'BassD', notes: CHORD_LIBRARY['BassD'], color: '#4E342E' },
      middle: { name: 'BassE', notes: CHORD_LIBRARY['BassE'], color: '#5D4037' },
      ring: { name: 'BassF', notes: CHORD_LIBRARY['BassF'], color: '#6D4C41' },
      pinky: { name: 'BassG', notes: CHORD_LIBRARY['BassG'], color: '#795548' },
    },
    right: {
      thumb: { name: 'BassA', notes: CHORD_LIBRARY['BassA'], color: '#8D6E63' },
      index: { name: 'BassB', notes: CHORD_LIBRARY['BassB'], color: '#A1887F' },
      middle: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#BCAAA4' },
      ring: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#D7CCC8' },
      pinky: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#EFEBE9' },
    },
  },

  // ==========================================
  // WOODWINDS
  // ==========================================
  {
    id: 'saxophone',
    name: 'Alto Saxophone',
    icon: 'saxophone',
    description: 'Smooth jazz saxophone',
    category: 'woodwinds',
    instrument: 65,
    left: {
      thumb: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#FFB347' },
      index: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#FFCC00' },
      middle: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#FF9966' },
      ring: { name: 'F4', notes: CHORD_LIBRARY['F4'], color: '#FFD700' },
      pinky: { name: 'G4', notes: CHORD_LIBRARY['G4'], color: '#FFA500' },
    },
    right: {
      thumb: { name: 'A4', notes: CHORD_LIBRARY['A4'], color: '#FF8C00' },
      index: { name: 'B4', notes: CHORD_LIBRARY['B4'], color: '#FF7F50' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#FF6347' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#FF4500' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#DC143C' },
    },
  },

  {
    id: 'tenor-sax',
    name: 'Tenor Saxophone',
    icon: 'saxophone',
    description: 'Rich tenor sax',
    category: 'woodwinds',
    instrument: 66,
    left: {
      thumb: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#CD853F' },
      index: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#DEB887' },
      middle: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#D2691E' },
      ring: { name: 'F4', notes: CHORD_LIBRARY['F4'], color: '#8B4513' },
      pinky: { name: 'G4', notes: CHORD_LIBRARY['G4'], color: '#A0522D' },
    },
    right: {
      thumb: { name: 'A4', notes: CHORD_LIBRARY['A4'], color: '#DAA520' },
      index: { name: 'B4', notes: CHORD_LIBRARY['B4'], color: '#B8860B' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#FFD700' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#FFA500' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#FF8C00' },
    },
  },

  {
    id: 'flute',
    name: 'Concert Flute',
    icon: 'flute',
    description: 'Airy classical flute',
    category: 'woodwinds',
    instrument: 73,
    left: {
      thumb: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#E0FFFF' },
      index: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#B0E0E6' },
      middle: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#87CEEB' },
      ring: { name: 'F5', notes: CHORD_LIBRARY['F5'], color: '#87CEFA' },
      pinky: { name: 'G5', notes: CHORD_LIBRARY['G5'], color: '#00BFFF' },
    },
    right: {
      thumb: { name: 'A5', notes: CHORD_LIBRARY['A5'], color: '#1E90FF' },
      index: { name: 'B5', notes: CHORD_LIBRARY['B5'], color: '#6495ED' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#4169E1' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#0000FF' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#0000CD' },
    },
  },

  {
    id: 'pan-flute',
    name: 'Pan Flute',
    icon: 'flute',
    description: 'Ethereal pan pipes',
    category: 'woodwinds',
    instrument: 75,
    left: {
      thumb: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#98FB98' },
      index: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#90EE90' },
      middle: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#8FBC8F' },
      ring: { name: 'F5', notes: CHORD_LIBRARY['F5'], color: '#3CB371' },
      pinky: { name: 'G5', notes: CHORD_LIBRARY['G5'], color: '#2E8B57' },
    },
    right: {
      thumb: { name: 'A5', notes: CHORD_LIBRARY['A5'], color: '#228B22' },
      index: { name: 'B5', notes: CHORD_LIBRARY['B5'], color: '#006400' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#32CD32' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#00FF00' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#7CFC00' },
    },
  },

  {
    id: 'clarinet',
    name: 'Clarinet',
    icon: 'flute',
    description: 'Rich woodwind clarinet',
    category: 'woodwinds',
    instrument: 71,
    left: {
      thumb: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#2F4F4F' },
      index: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#556B2F' },
      middle: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#6B8E23' },
      ring: { name: 'F4', notes: CHORD_LIBRARY['F4'], color: '#808000' },
      pinky: { name: 'G4', notes: CHORD_LIBRARY['G4'], color: '#9ACD32' },
    },
    right: {
      thumb: { name: 'A4', notes: CHORD_LIBRARY['A4'], color: '#32CD32' },
      index: { name: 'B4', notes: CHORD_LIBRARY['B4'], color: '#00FA9A' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#00FF7F' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#7FFF00' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#ADFF2F' },
    },
  },

  {
    id: 'oboe',
    name: 'Oboe',
    icon: 'flute',
    description: 'Expressive double reed',
    category: 'woodwinds',
    instrument: 68,
    left: {
      thumb: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#8B0000' },
      index: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#A52A2A' },
      middle: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#B22222' },
      ring: { name: 'F4', notes: CHORD_LIBRARY['F4'], color: '#DC143C' },
      pinky: { name: 'G4', notes: CHORD_LIBRARY['G4'], color: '#CD5C5C' },
    },
    right: {
      thumb: { name: 'A4', notes: CHORD_LIBRARY['A4'], color: '#F08080' },
      index: { name: 'B4', notes: CHORD_LIBRARY['B4'], color: '#FA8072' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#E9967A' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#FFA07A' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#FF7F50' },
    },
  },

  {
    id: 'bassoon',
    name: 'Bassoon',
    icon: 'flute',
    description: 'Deep orchestral bassoon',
    category: 'woodwinds',
    instrument: 70,
    left: {
      thumb: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#4A148C' },
      index: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#6A1B9A' },
      middle: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#7B1FA2' },
      ring: { name: 'F4', notes: CHORD_LIBRARY['F4'], color: '#8E24AA' },
      pinky: { name: 'G4', notes: CHORD_LIBRARY['G4'], color: '#9C27B0' },
    },
    right: {
      thumb: { name: 'A4', notes: CHORD_LIBRARY['A4'], color: '#AB47BC' },
      index: { name: 'B4', notes: CHORD_LIBRARY['B4'], color: '#BA68C8' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#CE93D8' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#E1BEE7' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#F3E5F5' },
    },
  },

  {
    id: 'recorder',
    name: 'Recorder',
    icon: 'flute',
    description: 'Sweet baroque recorder',
    category: 'woodwinds',
    instrument: 74,
    left: {
      thumb: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#FFF9C4' },
      index: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#FFF59D' },
      middle: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#FFF176' },
      ring: { name: 'F5', notes: CHORD_LIBRARY['F5'], color: '#FFEE58' },
      pinky: { name: 'G5', notes: CHORD_LIBRARY['G5'], color: '#FFEB3B' },
    },
    right: {
      thumb: { name: 'A5', notes: CHORD_LIBRARY['A5'], color: '#FDD835' },
      index: { name: 'B5', notes: CHORD_LIBRARY['B5'], color: '#FBC02D' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#F9A825' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#F57F17' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#FF8F00' },
    },
  },

  // ==========================================
  // SYNTH
  // ==========================================
  {
    id: 'lead-synth',
    name: 'Lead Synth',
    icon: 'synth',
    description: 'Bright synthesizer lead sounds',
    category: 'synth',
    instrument: 81,
    left: {
      thumb: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: NOTE_COLORS.neonCyan },
      index: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: NOTE_COLORS.neonGreen },
      middle: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: NOTE_COLORS.neonYellow },
      ring: { name: 'F4', notes: CHORD_LIBRARY['F4'], color: NOTE_COLORS.orange },
      pinky: { name: 'G4', notes: CHORD_LIBRARY['G4'], color: NOTE_COLORS.neonPink },
    },
    right: {
      thumb: { name: 'A4', notes: CHORD_LIBRARY['A4'], color: NOTE_COLORS.neonPurple },
      index: { name: 'B4', notes: CHORD_LIBRARY['B4'], color: NOTE_COLORS.blue },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: NOTE_COLORS.lime },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: NOTE_COLORS.yellow },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: NOTE_COLORS.magenta },
    },
  },

  {
    id: 'square-lead',
    name: 'Square Lead',
    icon: 'synth',
    description: 'Classic square wave lead',
    category: 'synth',
    instrument: 80,
    left: {
      thumb: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#00E5FF' },
      index: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#00B8D4' },
      middle: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#0097A7' },
      ring: { name: 'F4', notes: CHORD_LIBRARY['F4'], color: '#00838F' },
      pinky: { name: 'G4', notes: CHORD_LIBRARY['G4'], color: '#006064' },
    },
    right: {
      thumb: { name: 'A4', notes: CHORD_LIBRARY['A4'], color: '#18FFFF' },
      index: { name: 'B4', notes: CHORD_LIBRARY['B4'], color: '#84FFFF' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#A7FFEB' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#64FFDA' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#1DE9B6' },
    },
  },

  {
    id: 'pad-synth',
    name: 'Synth Pad',
    icon: 'wave',
    description: 'Warm evolving pad sounds',
    category: 'synth',
    instrument: 89,
    left: {
      thumb: { name: 'Cmaj7', notes: CHORD_LIBRARY['Cmaj7'], color: '#667eea' },
      index: { name: 'Dm7', notes: CHORD_LIBRARY['Dm7'], color: '#764ba2' },
      middle: { name: 'Em7', notes: CHORD_LIBRARY['Em7'], color: '#6B8DD6' },
      ring: { name: 'Fmaj7', notes: CHORD_LIBRARY['Fmaj7'], color: '#8E54E9' },
      pinky: { name: 'G7', notes: CHORD_LIBRARY['G7'], color: '#e94560' },
    },
    right: {
      thumb: { name: 'Am7', notes: CHORD_LIBRARY['Am7'], color: '#00fff5' },
      index: { name: 'Bm7', notes: CHORD_LIBRARY['Bm7'], color: '#00d9ff' },
      middle: { name: 'Cmaj7', notes: CHORD_LIBRARY['Cmaj7'], color: '#00b4ff' },
      ring: { name: 'Dm7', notes: CHORD_LIBRARY['Dm7'], color: '#0091ff' },
      pinky: { name: 'Em7', notes: CHORD_LIBRARY['Em7'], color: '#006eff' },
    },
  },

  {
    id: 'warm-pad',
    name: 'Warm Pad',
    icon: 'wave',
    description: 'Soft warm analog pad',
    category: 'synth',
    instrument: 89,
    left: {
      thumb: { name: 'C', notes: CHORD_LIBRARY['C'], color: '#FF8A80' },
      index: { name: 'Am', notes: CHORD_LIBRARY['Am'], color: '#FF80AB' },
      middle: { name: 'F', notes: CHORD_LIBRARY['F'], color: '#EA80FC' },
      ring: { name: 'G', notes: CHORD_LIBRARY['G'], color: '#B388FF' },
      pinky: { name: 'Em', notes: CHORD_LIBRARY['Em'], color: '#8C9EFF' },
    },
    right: {
      thumb: { name: 'Dm', notes: CHORD_LIBRARY['Dm'], color: '#82B1FF' },
      index: { name: 'Cmaj7', notes: CHORD_LIBRARY['Cmaj7'], color: '#80D8FF' },
      middle: { name: 'Fmaj7', notes: CHORD_LIBRARY['Fmaj7'], color: '#84FFFF' },
      ring: { name: 'Gmaj7', notes: CHORD_LIBRARY['Gmaj7'], color: '#A7FFEB' },
      pinky: { name: 'Am7', notes: CHORD_LIBRARY['Am7'], color: '#B9F6CA' },
    },
  },

  {
    id: 'retro-wave',
    name: 'Retrowave',
    icon: 'electronic',
    description: '80s synthwave vibes',
    category: 'synth',
    instrument: 85,
    left: {
      thumb: { name: 'Am', notes: CHORD_LIBRARY['Am'], color: '#FF1493' },
      index: { name: 'F', notes: CHORD_LIBRARY['F'], color: '#FF69B4' },
      middle: { name: 'C', notes: CHORD_LIBRARY['C'], color: '#DA70D6' },
      ring: { name: 'G', notes: CHORD_LIBRARY['G'], color: '#BA55D3' },
      pinky: { name: 'Em', notes: CHORD_LIBRARY['Em'], color: '#9400D3' },
    },
    right: {
      thumb: { name: 'Dm', notes: CHORD_LIBRARY['Dm'], color: '#00CED1' },
      index: { name: 'Am7', notes: CHORD_LIBRARY['Am7'], color: '#00FFFF' },
      middle: { name: 'Fmaj7', notes: CHORD_LIBRARY['Fmaj7'], color: '#7FFFD4' },
      ring: { name: 'Cmaj7', notes: CHORD_LIBRARY['Cmaj7'], color: '#40E0D0' },
      pinky: { name: 'G7', notes: CHORD_LIBRARY['G7'], color: '#48D1CC' },
    },
  },

  {
    id: 'fantasy-synth',
    name: 'Fantasy Synth',
    icon: 'synth',
    description: 'Dreamy fantasy soundscape',
    category: 'synth',
    instrument: 88,
    left: {
      thumb: { name: 'Cmaj7', notes: CHORD_LIBRARY['Cmaj7'], color: '#E1F5FE' },
      index: { name: 'Am7', notes: CHORD_LIBRARY['Am7'], color: '#B3E5FC' },
      middle: { name: 'Dm7', notes: CHORD_LIBRARY['Dm7'], color: '#81D4FA' },
      ring: { name: 'Gmaj7', notes: CHORD_LIBRARY['Gmaj7'], color: '#4FC3F7' },
      pinky: { name: 'Em7', notes: CHORD_LIBRARY['Em7'], color: '#29B6F6' },
    },
    right: {
      thumb: { name: 'Fmaj7', notes: CHORD_LIBRARY['Fmaj7'], color: '#03A9F4' },
      index: { name: 'Bm7', notes: CHORD_LIBRARY['Bm7'], color: '#039BE5' },
      middle: { name: 'Cmaj7', notes: CHORD_LIBRARY['Cmaj7'], color: '#0288D1' },
      ring: { name: 'Am7', notes: CHORD_LIBRARY['Am7'], color: '#0277BD' },
      pinky: { name: 'Dm7', notes: CHORD_LIBRARY['Dm7'], color: '#01579B' },
    },
  },

  // ==========================================
  // ELECTRONIC
  // ==========================================
  {
    id: 'dubstep-bass',
    name: 'Dubstep Bass',
    icon: 'electronic',
    description: 'Heavy wobble bass sounds',
    category: 'electronic',
    instrument: 38,
    left: {
      thumb: { name: 'BassC', notes: CHORD_LIBRARY['BassC'], color: '#8B00FF' },
      index: { name: 'BassD', notes: CHORD_LIBRARY['BassD'], color: '#9400D3' },
      middle: { name: 'BassE', notes: CHORD_LIBRARY['BassE'], color: '#9932CC' },
      ring: { name: 'BassF', notes: CHORD_LIBRARY['BassF'], color: '#BA55D3' },
      pinky: { name: 'BassG', notes: CHORD_LIBRARY['BassG'], color: '#DA70D6' },
    },
    right: {
      thumb: { name: 'BassA', notes: CHORD_LIBRARY['BassA'], color: '#EE82EE' },
      index: { name: 'BassB', notes: CHORD_LIBRARY['BassB'], color: '#FF00FF' },
      middle: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#FF69B4' },
      ring: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#FF1493' },
      pinky: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#FF007F' },
    },
  },

  {
    id: 'chiptune',
    name: 'Chiptune',
    icon: 'electronic',
    description: '8-bit retro game sounds',
    category: 'electronic',
    instrument: 80,
    left: {
      thumb: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#00FF00' },
      index: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#32CD32' },
      middle: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#7FFF00' },
      ring: { name: 'F4', notes: CHORD_LIBRARY['F4'], color: '#ADFF2F' },
      pinky: { name: 'G4', notes: CHORD_LIBRARY['G4'], color: '#00FF7F' },
    },
    right: {
      thumb: { name: 'A4', notes: CHORD_LIBRARY['A4'], color: '#00FFFF' },
      index: { name: 'B4', notes: CHORD_LIBRARY['B4'], color: '#00CED1' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#40E0D0' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#48D1CC' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#7FFFD4' },
    },
  },

  {
    id: 'sci-fi',
    name: 'Sci-Fi FX',
    icon: 'electronic',
    description: 'Futuristic sci-fi sounds',
    category: 'electronic',
    instrument: 103,
    left: {
      thumb: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#00BCD4' },
      index: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#00ACC1' },
      middle: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#0097A7' },
      ring: { name: 'F4', notes: CHORD_LIBRARY['F4'], color: '#00838F' },
      pinky: { name: 'G4', notes: CHORD_LIBRARY['G4'], color: '#006064' },
    },
    right: {
      thumb: { name: 'A4', notes: CHORD_LIBRARY['A4'], color: '#26C6DA' },
      index: { name: 'B4', notes: CHORD_LIBRARY['B4'], color: '#4DD0E1' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#80DEEA' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#B2EBF2' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#E0F7FA' },
    },
  },

  // ==========================================
  // ETHNIC / WORLD
  // ==========================================
  {
    id: 'sitar',
    name: 'Sitar',
    icon: 'sitar',
    description: 'Traditional Indian sitar',
    category: 'ethnic',
    instrument: 104,
    left: {
      thumb: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#FF6600' },
      index: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#FF9933' },
      middle: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#FFCC00' },
      ring: { name: 'F4', notes: CHORD_LIBRARY['F4'], color: '#FF6633' },
      pinky: { name: 'G4', notes: CHORD_LIBRARY['G4'], color: '#FF3300' },
    },
    right: {
      thumb: { name: 'A4', notes: CHORD_LIBRARY['A4'], color: '#CC3300' },
      index: { name: 'B4', notes: CHORD_LIBRARY['B4'], color: '#993300' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#996633' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#CC6600' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#FF9900' },
    },
  },

  {
    id: 'banjo',
    name: 'Banjo',
    icon: 'guitar',
    description: 'Twangy American banjo',
    category: 'ethnic',
    instrument: 105,
    left: {
      thumb: { name: 'G', notes: CHORD_LIBRARY['G'], color: '#FFA726' },
      index: { name: 'C', notes: CHORD_LIBRARY['C'], color: '#FFB74D' },
      middle: { name: 'D', notes: CHORD_LIBRARY['D'], color: '#FFCC80' },
      ring: { name: 'Em', notes: CHORD_LIBRARY['Em'], color: '#FFE0B2' },
      pinky: { name: 'Am', notes: CHORD_LIBRARY['Am'], color: '#FFF3E0' },
    },
    right: {
      thumb: { name: 'G7', notes: CHORD_LIBRARY['G7'], color: '#FF9800' },
      index: { name: 'C7', notes: CHORD_LIBRARY['C7'], color: '#FB8C00' },
      middle: { name: 'D7', notes: CHORD_LIBRARY['D7'], color: '#F57C00' },
      ring: { name: 'A7', notes: CHORD_LIBRARY['A7'], color: '#EF6C00' },
      pinky: { name: 'E7', notes: CHORD_LIBRARY['E7'], color: '#E65100' },
    },
  },

  {
    id: 'shamisen',
    name: 'Shamisen',
    icon: 'koto',
    description: 'Japanese three-stringed lute',
    category: 'ethnic',
    instrument: 106,
    left: {
      thumb: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#E8EAF6' },
      index: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#C5CAE9' },
      middle: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#9FA8DA' },
      ring: { name: 'F4', notes: CHORD_LIBRARY['F4'], color: '#7986CB' },
      pinky: { name: 'G4', notes: CHORD_LIBRARY['G4'], color: '#5C6BC0' },
    },
    right: {
      thumb: { name: 'A4', notes: CHORD_LIBRARY['A4'], color: '#3F51B5' },
      index: { name: 'B4', notes: CHORD_LIBRARY['B4'], color: '#3949AB' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#303F9F' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#283593' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#1A237E' },
    },
  },

  {
    id: 'koto',
    name: 'Koto',
    icon: 'koto',
    description: 'Japanese traditional koto',
    category: 'ethnic',
    instrument: 107,
    left: {
      thumb: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#DC143C' },
      index: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#B22222' },
      middle: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#8B0000' },
      ring: { name: 'F4', notes: CHORD_LIBRARY['F4'], color: '#800000' },
      pinky: { name: 'G4', notes: CHORD_LIBRARY['G4'], color: '#A52A2A' },
    },
    right: {
      thumb: { name: 'A4', notes: CHORD_LIBRARY['A4'], color: '#CD5C5C' },
      index: { name: 'B4', notes: CHORD_LIBRARY['B4'], color: '#F08080' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#FA8072' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#E9967A' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#FFA07A' },
    },
  },

  {
    id: 'kalimba',
    name: 'Kalimba',
    icon: 'mallet',
    description: 'African thumb piano',
    category: 'ethnic',
    instrument: 108,
    left: {
      thumb: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#8B4513' },
      index: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#A0522D' },
      middle: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#CD853F' },
      ring: { name: 'F5', notes: CHORD_LIBRARY['F5'], color: '#DEB887' },
      pinky: { name: 'G5', notes: CHORD_LIBRARY['G5'], color: '#D2691E' },
    },
    right: {
      thumb: { name: 'A5', notes: CHORD_LIBRARY['A5'], color: '#F4A460' },
      index: { name: 'B5', notes: CHORD_LIBRARY['B5'], color: '#FFDAB9' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#FFE4B5' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#FFE4C4' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#FFEFD5' },
    },
  },

  {
    id: 'bagpipe',
    name: 'Bagpipe',
    icon: 'flute',
    description: 'Scottish highland bagpipes',
    category: 'ethnic',
    instrument: 109,
    left: {
      thumb: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#1B5E20' },
      index: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#2E7D32' },
      middle: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#388E3C' },
      ring: { name: 'F4', notes: CHORD_LIBRARY['F4'], color: '#43A047' },
      pinky: { name: 'G4', notes: CHORD_LIBRARY['G4'], color: '#4CAF50' },
    },
    right: {
      thumb: { name: 'A4', notes: CHORD_LIBRARY['A4'], color: '#66BB6A' },
      index: { name: 'B4', notes: CHORD_LIBRARY['B4'], color: '#81C784' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#A5D6A7' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#C8E6C9' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#E8F5E9' },
    },
  },

  {
    id: 'steel-drums',
    name: 'Steel Drums',
    icon: 'drum',
    description: 'Caribbean steel pan drums',
    category: 'ethnic',
    instrument: 114,
    left: {
      thumb: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#FFEB3B' },
      index: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#FFC107' },
      middle: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#FF9800' },
      ring: { name: 'F4', notes: CHORD_LIBRARY['F4'], color: '#FF5722' },
      pinky: { name: 'G4', notes: CHORD_LIBRARY['G4'], color: '#F44336' },
    },
    right: {
      thumb: { name: 'A4', notes: CHORD_LIBRARY['A4'], color: '#E91E63' },
      index: { name: 'B4', notes: CHORD_LIBRARY['B4'], color: '#9C27B0' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#673AB7' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#3F51B5' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#2196F3' },
    },
  },

  // ==========================================
  // PERCUSSION
  // ==========================================
  {
    id: 'drums',
    name: 'Drum Kit',
    icon: 'drum',
    description: 'Full acoustic drum kit',
    category: 'percussion',
    instrument: 0,
    left: {
      thumb: { name: 'Kick', notes: CHORD_LIBRARY['Kick'], color: '#2C3E50' },
      index: { name: 'Snare', notes: CHORD_LIBRARY['Snare'], color: '#E74C3C' },
      middle: { name: 'HiHat', notes: CHORD_LIBRARY['HiHat'], color: '#F39C12' },
      ring: { name: 'Tom1', notes: CHORD_LIBRARY['Tom1'], color: '#27AE60' },
      pinky: { name: 'Tom2', notes: CHORD_LIBRARY['Tom2'], color: '#3498DB' },
    },
    right: {
      thumb: { name: 'Crash', notes: CHORD_LIBRARY['Crash'], color: '#9B59B6' },
      index: { name: 'Ride', notes: CHORD_LIBRARY['Ride'], color: '#1ABC9C' },
      middle: { name: 'HiHatOpen', notes: CHORD_LIBRARY['HiHatOpen'], color: '#E67E22' },
      ring: { name: 'Clap', notes: CHORD_LIBRARY['Clap'], color: '#E91E63' },
      pinky: { name: 'SideStick', notes: CHORD_LIBRARY['SideStick'], color: '#00BCD4' },
    },
  },

  {
    id: 'electronic-drums',
    name: 'Electronic Kit',
    icon: 'electronic',
    description: 'Punchy electronic percussion',
    category: 'percussion',
    instrument: 0,
    left: {
      thumb: { name: 'Kick2', notes: CHORD_LIBRARY['Kick2'], color: '#6C5CE7' },
      index: { name: 'Snare2', notes: CHORD_LIBRARY['Snare2'], color: '#FD79A8' },
      middle: { name: 'HiHat', notes: CHORD_LIBRARY['HiHat'], color: '#FFEAA7' },
      ring: { name: 'Tom3', notes: CHORD_LIBRARY['Tom3'], color: '#00CEC9' },
      pinky: { name: 'Tom4', notes: CHORD_LIBRARY['Tom4'], color: '#0984E3' },
    },
    right: {
      thumb: { name: 'Crash2', notes: CHORD_LIBRARY['Crash2'], color: '#A29BFE' },
      index: { name: 'RideBell', notes: CHORD_LIBRARY['RideBell'], color: '#55EFC4' },
      middle: { name: 'Cowbell', notes: CHORD_LIBRARY['Cowbell'], color: '#FDCB6E' },
      ring: { name: 'Tambourine', notes: CHORD_LIBRARY['Tambourine'], color: '#E17055' },
      pinky: { name: 'Clap', notes: CHORD_LIBRARY['Clap'], color: '#74B9FF' },
    },
  },

  {
    id: 'glockenspiel',
    name: 'Glockenspiel',
    icon: 'mallet',
    description: 'Bright metallic bells',
    category: 'percussion',
    instrument: 9,
    left: {
      thumb: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#E3F2FD' },
      index: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#BBDEFB' },
      middle: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#90CAF9' },
      ring: { name: 'F5', notes: CHORD_LIBRARY['F5'], color: '#64B5F6' },
      pinky: { name: 'G5', notes: CHORD_LIBRARY['G5'], color: '#42A5F5' },
    },
    right: {
      thumb: { name: 'A5', notes: CHORD_LIBRARY['A5'], color: '#2196F3' },
      index: { name: 'B5', notes: CHORD_LIBRARY['B5'], color: '#1E88E5' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#1976D2' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#1565C0' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#0D47A1' },
    },
  },

  {
    id: 'music-box',
    name: 'Music Box',
    icon: 'bell',
    description: 'Delicate music box tones',
    category: 'percussion',
    instrument: 10,
    left: {
      thumb: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#FCE4EC' },
      index: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#F8BBD9' },
      middle: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#F48FB1' },
      ring: { name: 'F5', notes: CHORD_LIBRARY['F5'], color: '#F06292' },
      pinky: { name: 'G5', notes: CHORD_LIBRARY['G5'], color: '#EC407A' },
    },
    right: {
      thumb: { name: 'A5', notes: CHORD_LIBRARY['A5'], color: '#E91E63' },
      index: { name: 'B5', notes: CHORD_LIBRARY['B5'], color: '#D81B60' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#C2185B' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#AD1457' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#880E4F' },
    },
  },

  {
    id: 'vibraphone',
    name: 'Vibraphone',
    icon: 'mallet',
    description: 'Shimmering jazz vibraphone',
    category: 'percussion',
    instrument: 11,
    left: {
      thumb: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#C0C0C0' },
      index: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#D3D3D3' },
      middle: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#A9A9A9' },
      ring: { name: 'F4', notes: CHORD_LIBRARY['F4'], color: '#808080' },
      pinky: { name: 'G4', notes: CHORD_LIBRARY['G4'], color: '#696969' },
    },
    right: {
      thumb: { name: 'A4', notes: CHORD_LIBRARY['A4'], color: '#778899' },
      index: { name: 'B4', notes: CHORD_LIBRARY['B4'], color: '#708090' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#B0C4DE' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#ADD8E6' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#87CEEB' },
    },
  },

  {
    id: 'marimba',
    name: 'Marimba',
    icon: 'mallet',
    description: 'Warm wooden marimba',
    category: 'percussion',
    instrument: 12,
    left: {
      thumb: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#8B4513' },
      index: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#A0522D' },
      middle: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#CD853F' },
      ring: { name: 'F4', notes: CHORD_LIBRARY['F4'], color: '#DEB887' },
      pinky: { name: 'G4', notes: CHORD_LIBRARY['G4'], color: '#D2691E' },
    },
    right: {
      thumb: { name: 'A4', notes: CHORD_LIBRARY['A4'], color: '#F4A460' },
      index: { name: 'B4', notes: CHORD_LIBRARY['B4'], color: '#FFDAB9' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#FFE4B5' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#FFE4C4' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#FFEFD5' },
    },
  },

  {
    id: 'xylophone',
    name: 'Xylophone',
    icon: 'mallet',
    description: 'Bright wooden xylophone',
    category: 'percussion',
    instrument: 13,
    left: {
      thumb: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#FFCDD2' },
      index: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#EF9A9A' },
      middle: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#E57373' },
      ring: { name: 'F5', notes: CHORD_LIBRARY['F5'], color: '#EF5350' },
      pinky: { name: 'G5', notes: CHORD_LIBRARY['G5'], color: '#F44336' },
    },
    right: {
      thumb: { name: 'A5', notes: CHORD_LIBRARY['A5'], color: '#E53935' },
      index: { name: 'B5', notes: CHORD_LIBRARY['B5'], color: '#D32F2F' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#C62828' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#B71C1C' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#FF8A80' },
    },
  },

  {
    id: 'tubular-bells',
    name: 'Tubular Bells',
    icon: 'bell',
    description: 'Orchestral chimes',
    category: 'percussion',
    instrument: 14,
    left: {
      thumb: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#CFD8DC' },
      index: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#B0BEC5' },
      middle: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#90A4AE' },
      ring: { name: 'F4', notes: CHORD_LIBRARY['F4'], color: '#78909C' },
      pinky: { name: 'G4', notes: CHORD_LIBRARY['G4'], color: '#607D8B' },
    },
    right: {
      thumb: { name: 'A4', notes: CHORD_LIBRARY['A4'], color: '#546E7A' },
      index: { name: 'B4', notes: CHORD_LIBRARY['B4'], color: '#455A64' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#37474F' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#263238' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#ECEFF1' },
    },
  },

  {
    id: 'timpani',
    name: 'Timpani',
    icon: 'drum',
    description: 'Orchestral kettle drums',
    category: 'percussion',
    instrument: 47,
    left: {
      thumb: { name: 'C4', notes: CHORD_LIBRARY['C4'], color: '#4E342E' },
      index: { name: 'D4', notes: CHORD_LIBRARY['D4'], color: '#5D4037' },
      middle: { name: 'E4', notes: CHORD_LIBRARY['E4'], color: '#6D4C41' },
      ring: { name: 'F4', notes: CHORD_LIBRARY['F4'], color: '#795548' },
      pinky: { name: 'G4', notes: CHORD_LIBRARY['G4'], color: '#8D6E63' },
    },
    right: {
      thumb: { name: 'A4', notes: CHORD_LIBRARY['A4'], color: '#A1887F' },
      index: { name: 'B4', notes: CHORD_LIBRARY['B4'], color: '#BCAAA4' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#D7CCC8' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#EFEBE9' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#3E2723' },
    },
  },

  // ==========================================
  // AMBIENT
  // ==========================================
  {
    id: 'ambient-pad',
    name: 'Ambient Pad',
    icon: 'wave',
    description: 'Ethereal atmospheric textures',
    category: 'ambient',
    instrument: 89,
    left: {
      thumb: { name: 'Csus2', notes: CHORD_LIBRARY['Csus2'], color: '#667eea' },
      index: { name: 'Gsus2', notes: CHORD_LIBRARY['Gsus2'], color: '#764ba2' },
      middle: { name: 'Fsus2', notes: CHORD_LIBRARY['Fsus2'], color: '#6B8DD6' },
      ring: { name: 'Am', notes: CHORD_LIBRARY['Am'], color: '#8E54E9' },
      pinky: { name: 'Em', notes: CHORD_LIBRARY['Em'], color: '#e94560' },
    },
    right: {
      thumb: { name: 'Cmaj7', notes: CHORD_LIBRARY['Cmaj7'], color: '#00fff5' },
      index: { name: 'Fmaj7', notes: CHORD_LIBRARY['Fmaj7'], color: '#00d9ff' },
      middle: { name: 'Gmaj7', notes: CHORD_LIBRARY['Gmaj7'], color: '#00b4ff' },
      ring: { name: 'Am7', notes: CHORD_LIBRARY['Am7'], color: '#0091ff' },
      pinky: { name: 'Em7', notes: CHORD_LIBRARY['Em7'], color: '#006eff' },
    },
  },

  {
    id: 'space-ambient',
    name: 'Space Ambient',
    icon: 'wave',
    description: 'Deep space soundscapes',
    category: 'ambient',
    instrument: 94,
    left: {
      thumb: { name: 'Cmaj7', notes: CHORD_LIBRARY['Cmaj7'], color: '#0D1B2A' },
      index: { name: 'Am7', notes: CHORD_LIBRARY['Am7'], color: '#1B263B' },
      middle: { name: 'Dm7', notes: CHORD_LIBRARY['Dm7'], color: '#415A77' },
      ring: { name: 'Gmaj7', notes: CHORD_LIBRARY['Gmaj7'], color: '#778DA9' },
      pinky: { name: 'Em7', notes: CHORD_LIBRARY['Em7'], color: '#E0E1DD' },
    },
    right: {
      thumb: { name: 'Fmaj7', notes: CHORD_LIBRARY['Fmaj7'], color: '#4CC9F0' },
      index: { name: 'Bm7', notes: CHORD_LIBRARY['Bm7'], color: '#4895EF' },
      middle: { name: 'Cmaj7', notes: CHORD_LIBRARY['Cmaj7'], color: '#4361EE' },
      ring: { name: 'Am7', notes: CHORD_LIBRARY['Am7'], color: '#3F37C9' },
      pinky: { name: 'Dm7', notes: CHORD_LIBRARY['Dm7'], color: '#7209B7' },
    },
  },

  {
    id: 'celestial',
    name: 'Celestial Bells',
    icon: 'bell',
    description: 'Heavenly bell textures',
    category: 'ambient',
    instrument: 88,
    left: {
      thumb: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#E0FFFF' },
      index: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#B0E0E6' },
      middle: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#AFEEEE' },
      ring: { name: 'F5', notes: CHORD_LIBRARY['F5'], color: '#00CED1' },
      pinky: { name: 'G5', notes: CHORD_LIBRARY['G5'], color: '#48D1CC' },
    },
    right: {
      thumb: { name: 'A5', notes: CHORD_LIBRARY['A5'], color: '#40E0D0' },
      index: { name: 'B5', notes: CHORD_LIBRARY['B5'], color: '#00FFFF' },
      middle: { name: 'C5', notes: CHORD_LIBRARY['C5'], color: '#7FFFD4' },
      ring: { name: 'D5', notes: CHORD_LIBRARY['D5'], color: '#66CDAA' },
      pinky: { name: 'E5', notes: CHORD_LIBRARY['E5'], color: '#5F9EA0' },
    },
  },

  {
    id: 'choir',
    name: 'Choir Aahs',
    icon: 'wave',
    description: 'Angelic choir voices',
    category: 'ambient',
    instrument: 52,
    left: {
      thumb: { name: 'C', notes: CHORD_LIBRARY['C'], color: '#F3E5F5' },
      index: { name: 'Am', notes: CHORD_LIBRARY['Am'], color: '#E1BEE7' },
      middle: { name: 'F', notes: CHORD_LIBRARY['F'], color: '#CE93D8' },
      ring: { name: 'G', notes: CHORD_LIBRARY['G'], color: '#BA68C8' },
      pinky: { name: 'Em', notes: CHORD_LIBRARY['Em'], color: '#AB47BC' },
    },
    right: {
      thumb: { name: 'Dm', notes: CHORD_LIBRARY['Dm'], color: '#9C27B0' },
      index: { name: 'Cmaj7', notes: CHORD_LIBRARY['Cmaj7'], color: '#8E24AA' },
      middle: { name: 'Fmaj7', notes: CHORD_LIBRARY['Fmaj7'], color: '#7B1FA2' },
      ring: { name: 'Gmaj7', notes: CHORD_LIBRARY['Gmaj7'], color: '#6A1B9A' },
      pinky: { name: 'Am7', notes: CHORD_LIBRARY['Am7'], color: '#4A148C' },
    },
  },

  {
    id: 'voice-oohs',
    name: 'Voice Oohs',
    icon: 'wave',
    description: 'Soft vocal oohs',
    category: 'ambient',
    instrument: 53,
    left: {
      thumb: { name: 'C', notes: CHORD_LIBRARY['C'], color: '#FFEBEE' },
      index: { name: 'Am', notes: CHORD_LIBRARY['Am'], color: '#FFCDD2' },
      middle: { name: 'F', notes: CHORD_LIBRARY['F'], color: '#EF9A9A' },
      ring: { name: 'G', notes: CHORD_LIBRARY['G'], color: '#E57373' },
      pinky: { name: 'Dm', notes: CHORD_LIBRARY['Dm'], color: '#EF5350' },
    },
    right: {
      thumb: { name: 'Em', notes: CHORD_LIBRARY['Em'], color: '#F44336' },
      index: { name: 'Cmaj7', notes: CHORD_LIBRARY['Cmaj7'], color: '#E53935' },
      middle: { name: 'Fmaj7', notes: CHORD_LIBRARY['Fmaj7'], color: '#D32F2F' },
      ring: { name: 'Am7', notes: CHORD_LIBRARY['Am7'], color: '#C62828' },
      pinky: { name: 'Gmaj7', notes: CHORD_LIBRARY['Gmaj7'], color: '#B71C1C' },
    },
  },
];

// Get instrument by ID
export const getInstrumentById = (id: string): InstrumentPreset | undefined => {
  return INSTRUMENTS.find(inst => inst.id === id);
};

// Get instruments by category
export const getInstrumentsByCategory = (category: string): InstrumentPreset[] => {
  return INSTRUMENTS.filter(inst => inst.category === category);
};

// Default instrument
export const DEFAULT_INSTRUMENT_ID = 'piano';
